### ISSUE TITLE
After 26 participants, participants are added outside of the canvas

### ISSUE THREAD

**Issue by NCEghtebas** [TUMFARSynchrony/experimental-hub#146]
Below image shows the last possible participant that can be rendered. Qucik fix is to start another row after 26 P's. 

![Image](https://github.com/TUMFARSynchrony/experimental-hub/assets/1645633/96e2e25c-f71e-4e4b-8975-b02035631f87)

This could be an issue beacuse if somehow 26 participants are created and deleted in a session, new participants cannot be easily accessed.

**Comment by mertyldrr** [comment]
I'll look into this. formed shape(with different colors) looks nice tho 😄

**Comment by bikemc** [comment]
@mertyldrr  I think you can close this issue :)

**Comment by NCEghtebas** [comment]
Solved with PR #148
