### ISSUE TITLE
Reconnection of participant does not always work

### ISSUE THREAD

**Issue by BorderBoy** [TUMFARSynchrony/experimental-hub#200]
When a participant reconnects it can lead to state where the participant is connected, but the experimenter cannot see the video stream of the participant. It just show a black square or nothing at all.

# How to reproduce?
1. Start and join session as Experimenter using session overview.
2. Join experiment with 2 participant using the lobby link.
3. Wait until everybody is connected.
4. Reload page of one of the two participants.

Here is an overview of combinations and if reconnection works or not.
Participant \ Experimenter | Normal | Connection Test
---------------------------|---------|-----------------
**Normal**                             |❌         |✔️ 
**Connection Test**                |✔️         |✔️

**Comment by BorderBoy** [comment]
This is releated to #152 and #156

**Comment by MEnesDeniz** [comment]
I have tried this in with the proposed solution in here https://github.com/TUMFARSynchrony/experimental-hub/pull/234 and I could not replicate the black screen problem.

**Comment by NCEghtebas** [comment]
Potentially also related to [#152](https://github.com/TUMFARSynchrony/experimental-hub/issues/152)
