### ISSUE TITLE
Show instructions tab in display mode for the meeting room page

### ISSUE THREAD

**Issue by gulbikeimge** [TUMFARSynchrony/experimental-hub#248]
On the meeting room page, participants are able to check the checkboxes in the instructions tab. This functionality is not intended because the purpose of the checkboxes is to ensure participants have read and agreed to the instructions on the lobby page, which is meant to be completed before entering the meeting room page. The checkboxes should only be interactable on the lobby page, not on the meeting room page.

**Comment by NCEghtebas** [comment]
Solved with PR https://github.com/TUMFARSynchrony/experimental-hub/pull/250
