### ISSUE TITLE
Implement audio and video stream recording

### ISSUE THREAD

**Issue by normaps** [TUMFARSynchrony/experimental-hub#36]
# Recording Implementation

## Description
Video data from the experiment is necessary for further analysis of synchrony. Therefore, a recording feature would be very beneficial for future researchers, as they can turn the videos into some facial extraction files through OpenFace / PyFeat or any other tools.

## Workflow
1.  An experiment can be recorded if the "record" field is checked when creating the experiment
2. The recording will start at the same time as the experiment starts and stop when the experiment ends.
3. The result will be saved in the `sessions` folder based on the `session_id` of the experiment. Each participant will have two files, audio and video with format `participantId_date_timestamp.mp3/mp4`

## Use Cases
- [ ] A participant joins first then the experiment starts.  Result: black screen is there but the audio recording is fine
- [x] The experiment starts and the participant joins later.
- [ ] Two participants join first then the experiment starts. Result: black screen is there but the audio recording is fine
- [x] The experiment starts and two participants join later.
- [x] Recording must stop when the experiment ends.
- [x] One of the participants leaves during the experiment. Result: the recorded video is shorter than others.
- [ ] Participants disconnect during the experiment and joins again later. Result: only first joined connection would be recorded. After she joined again, the recording doesn't start again.

## Improvements and Discussions
- How to handle a participant that joins later after the experiment starts.
- Maximum time of the experiment because this concerns the recording result size.

**Comment by BorderBoy** [comment]
Should this issue be closed or is there still more to do?

**Comment by normaps** [comment]
> Should this issue be closed or is there still more to do?

Thanks Jonas for checking! All should be done, and we can close it. We can create new issues if we have something to fix/improve
