### ISSUE TITLE
AU filter with AUExtractor

### ISSUE THREAD

**Issue by KuroiX** [TUMFARSynchrony/experimental-hub#37]
Implement AU filter based on abstraction AUExtractor from the Synchrony Score git.

The abstraction allows to switch between different ways to extract AUs later on. 

The extract call is done via parallel processes in python, so that extracting the AUs does not bottleneck the pipeline. After calling the parallel extract, the filter skips every frame until the extraction is done, then adds the result to a either a timeseries of AUs or just a "current AU" variable for further processing.

**Comment by NCEghtebas** [comment]
We have an AU extractor filter that calls Openface and returns action units 12 and 6.
